version: 0.1
storage:
  s3:
    region: us-east-2
    bucket: tharani-reg
    encrypt: true
    secure: true
    v4auth: true
    chunksize: 5242880
    multipartcopychunksize: 33554432
    multipartcopymaxconcurrency: 100
    multipartcopythresholdsize: 33554432
  cache:
    blobdescriptor: inmemory

http:
  addr: ":5000"
  secret: "a-secret"
  debug:
    addr: ":5001"
  headers:
    X-Content-Type-Options: [ "nosniff" ]
health:
  storagedriver:
    enabled: true
    interval: "10s"
    threshold: 3
