version: '3'
services:
  reverse-proxy: 
    image: localhost:5000/nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  simple-web:
    image: localhost:5000/simple-web
    restart: always

  simple-web1:
    image: localhost:5000/simple-web
    restart: always
 
